# -*- coding: utf-8 -*-
"""studmodel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m6FaRwACHJCK80xEZ_pJSnKhSOdTyGeI
"""

#1. Import necessary libraries
import matplotlib.pyplot as plt
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn import tree
from sklearn import svm
import pandas as pd



#2. Load the dataset
df = pd.read_csv("Students Social Media Addiction.csv")
student = pd.read_csv("Students Social Media Addiction.csv")

#check data
student

X = df.drop("Addicted_Score", axis=1)
y = df["Addicted_Score"]

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

categorical_cols = X.select_dtypes(include="object").columns
numeric_cols = X.select_dtypes(exclude="object").columns

preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols),
        ("num", "passthrough", numeric_cols)
    ]
)

X_encoded = preprocessor.fit_transform(X)

#3. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42
)
X_train.shape
X_test.shape
y_train.shape
y_test.shape
classifier = svm.SVC(kernel='linear')

#4. Create and train the Decision Tree classifier
treemodel=DecisionTreeClassifier()
treemodel.fit(X_train,y_train)

plt.figure(figsize=(25,12))
tree.plot_tree(
    treemodel,
    feature_names=X.columns,
    class_names=[str(c) for c in sorted(y.unique())],
    filled=True,
    rounded=True,
    fontsize=10
)
plt.show()

#5.Used the learned model to prediction with the test set
y_pred = treemodel.predict(X_test)
y_pred

#6. Evaluate model accuracy
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

# 6. Feature Importance
import numpy as np
importances = treemodel.feature_importances_
sorted_idx = np.argsort(importances)[::-1]

print("\nFeature Importance Ranking:")
for idx in sorted_idx:
    print(f"{X.columns[idx]}: {importances[idx]}")

#7. Confusion matrix Visualisation
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
cm = confusion_matrix(y_test, y_pred)
labels = [str(x) for x in sorted(y.unique())]
plt.figure(figsize=(10, 8))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=labels)
disp.plot(cmap=plt.cm.Blues, values_format='d')
plt.title("Confusion Matrix – Decision Tree Model for Student Social Media Addiction")
plt.xlabel("Predicted Addiction Score")
plt.ylabel("Actual Addiction Score")
plt.show()

print("Columns in Dataset:", df.columns.tolist())
print("Dataset shape:", df.shape)

#Decision tree optimization
depth_options = [3, 5, 7, None]     # None = unlimited depth
criteria = ["gini", "entropy"]

tuning_results = []

for depth in depth_options:
    for crit in criteria:
        model_t = DecisionTreeClassifier(
            max_depth=depth,
            criterion=crit,
            random_state=42
        )
        model_t.fit(X_train, y_train)
        preds_t = model_t.predict(X_test)
        acc = accuracy_score(y_test, preds_t)

        tuning_results.append((depth, crit, acc))

print("\n=== Decision Tree Optimization Results ===")
for depth, crit, acc in tuning_results:
    print(f"Depth={depth}, Criterion={crit}, Accuracy={acc:.4f}")

#pickle the file
from sklearn.pipeline import Pipeline
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
import pickle

model = DecisionTreeClassifier(random_state=42)

pipeline = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("classifier", model)
])

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

pipeline.fit(X_train, y_train)

y_pred = treemodel.predict(X_test)
y_pred

with open("addiction_model.pkl", "wb") as file:
    pickle.dump(pipeline, file)

